metatag.metatag_tag.pinterest_description:
  type: label
  label: 'Pinterest: Description'
metatag.metatag_tag.pinterest_id:
  type: label
  label: 'Pinterest: ID'
metatag.metatag_tag.pinterest_media:
  type: label
  label: 'Pinterest: Media'
metatag.metatag_tag.pinterest_nohover:
  type: label
  label: 'Pinterest: No hover'
metatag.metatag_tag.pinterest_nopin:
  type: label
  label: 'Pinterest: No pin'
metatag.metatag_tag.pinterest_nosearch:
  type: label
  label: 'Pinterest: No search'
metatag.metatag_tag.pinterest_url:
  type: label
  label: 'Pinterest: URL'
