<?php

/**
 * Implements hook_ctools_plugin_directory().
 */
function metatag_ui_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && $plugin == 'export_ui') {
    //return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_menu().
 */
function metatag_ui_menu() {
  $items['admin/config/search/metatags'] = array(
    'title' => 'Meta tags',
    'description' => 'Configure meta tag defaults.',
    'page callback' => 'metatag_ui_config_overview',
    'access arguments' => array('administer meta tags'),
    'file' => 'metatag_ui.admin.inc',
  );
  $items['admin/config/search/metatags/add'] = array(
    'title' => 'Add configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('metatag_ui_config_add_form'),
    'access arguments' => array('administer meta tags'),
    'file' => 'metatag_ui.admin.inc',
    'type' => MENU_LOCAL_ACTION,
  );
  $items['admin/config/search/metatags/%metatag_config'] = array(
    'title' => 'Edit configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('metatag_ui_config_edit_form', 5),
    'access arguments' => array('administer meta tags'),
    'file' => 'metatag_ui.admin.inc',
  );
  $items['admin/config/search/metatags/%metatag_config/edit'] = array(
    'title' => 'Edit',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/config/search/metatags/%metatags_config/export'] = array(
    'title' => 'Export',
    'page callback' => 'metatag_ui_config_export_form',
    'page arguments' => array(5),
    'access arguments' => array('administer meta tags'),
    'file' => 'metatag_ui.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}
